#name: Deploy Logye to EC2 via SSH

#on:
#  push:
#    branches:
#      - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout source
#         uses: actions/checkout@v3

#       - name: SSH & Deploy
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USERNAME }}
#           key: ${{ secrets.EC2_SSH_KEY }}
#           script: |
#             cd /home/ec2-user/deploy
#             git pull origin main
#             docker compose down
#             docker compose build
#             docker compose up -d
